name: Upload release assets

# this flow will be run only when new tags are pushed that match our pattern
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Version in common/version.h must match release tag
        run: |
          export CANBOAT_VERSION=$(sed -En 's/.*\ VERSION\ \"([0-9]+\.)([0-9]+\.)?([0-9]+)\"/\1\2\3/p' common/version.h)
          echo "Checking if docs/canboat.json contains \"CANboat version v${CANBOAT_VERSION}\""
          grep -q "CANboat version v${CANBOAT_VERSION}" docs/canboat.json
          echo "Checking if docs/canboat.json contains version \"Version\":\"${CANBOAT_VERSION}\""
          grep -q "\"Version\":\"${CANBOAT_VERSION}\"" docs/canboat.json
          echo "Checking if docs/canboat.xml contains \"CANboat version v${CANBOAT_VERSION}\""
          grep -q "CANboat version v${CANBOAT_VERSION}" docs/canboat.xml
          echo "Checking if docs/canboat.xml contains \"<Version>${CANBOAT_VERSION}</Version>\""
          grep -q "<Version>${CANBOAT_VERSION}</Version>" docs/canboat.xml
          export SCHEMA_VERSION=$(sed -En 's/.*\ SCHEMA_VERSION\ \"([0-9]+\.)([0-9]+\.)?([0-9]+)\"/\1\2\3/p' common/version.h)
          echo "Checking if docs/canboat.xsd contains \"xs:version=\"${SCHEMA_VERSION}\""
          grep -q "xs:schema version=\"${SCHEMA_VERSION}\"" docs/canboat.xsd
          echo "Checking if docs/canboat.json contains version \"SchemaVersion\":\"${SCHEMA_VERSION}\""
          grep -q "\"SchemaVersion\":\"${SCHEMA_VERSION}\"" docs/canboat.json
          echo "Github tag should match version in common/version.h"
          test "${GITHUB_REF##*/}" == "v${CANBOAT_VERSION}"

      - name: Add release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            docs/canboat.json
            docs/canboat.xml
            docs/canboat.xsd
